[book]
title = "PNG D2 Demo"
authors = ["You"]
src = "src"

[preprocessor.d2-png]
path = "d2"
layout = "dagre"
inline = false
output-dir = "diagrams"

[output.html]

[output.markdown]

[output.pdf]
optional = true
